package org.jalse.net;

public enum JALSEOperation {

    ADD_CLUSTER, KILL_CLUSTER, UPDATE_CLUSTER_ATTR, REMOVE_CLUSTER_ATTR, ADD_AGENT, KILL_AGENT, UPDATE_AGENT_ATTR,
    REMOVE_AGENT_ATTR, AUTHENTICATE, PERMISSIONS, ATTRIBUTE_TYPE, HELLO, GOODBYE
}
